

#ifndef   Mega2560_h_
#define   Mega2560_h_


#define   pio__D0_PinID    0
#define   pio__D0_BIT       BIT0
#define   pio__D0_DDR       DDRE
#define   pio__D0_PIN       PINE
#define   pio__D0_PORT      PORTE
#define   pio__D1_PinID    1
#define   pio__D1_BIT       BIT1
#define   pio__D1_DDR       DDRE
#define   pio__D1_PIN       PINE
#define   pio__D1_PORT      PORTE
#define   pio__D2_PinID    2
#define   pio__D2_BIT       BIT4
#define   pio__D2_DDR       DDRE
#define   pio__D2_PIN       PINE
#define   pio__D2_PORT      PORTE
#define   pio__D3_PinID    3
#define   pio__D3_BIT       BIT5
#define   pio__D3_DDR       DDRE
#define   pio__D3_PIN       PINE
#define   pio__D3_PORT      PORTE
#define   pio__D4_PinID    4
#define   pio__D4_BIT       BIT5
#define   pio__D4_DDR       DDRG
#define   pio__D4_PIN       PING
#define   pio__D4_PORT      PORTG
#define   pio__D5_PinID    5
#define   pio__D5_BIT       BIT3
#define   pio__D5_DDR       DDRE
#define   pio__D5_PIN       PINE
#define   pio__D5_PORT      PORTE
#define   pio__D6_PinID    6
#define   pio__D6_BIT       BIT3
#define   pio__D6_DDR       DDRH
#define   pio__D6_PIN       PINH
#define   pio__D6_PORT      PORTH
#define   pio__D7_PinID    7
#define   pio__D7_BIT       BIT4
#define   pio__D7_DDR       DDRH
#define   pio__D7_PIN       PINH
#define   pio__D7_PORT      PORTH
#define   pio__D8_PinID    8
#define   pio__D8_BIT       BIT5
#define   pio__D8_DDR       DDRH
#define   pio__D8_PIN       PINH
#define   pio__D8_PORT      PORTH
#define   pio__D9_PinID    9
#define   pio__D9_BIT       BIT6
#define   pio__D9_DDR       DDRH
#define   pio__D9_PIN       PINH
#define   pio__D9_PORT      PORTH
#define   pio__D10_PinID    10
#define   pio__D10_BIT       BIT4
#define   pio__D10_DDR       DDRB
#define   pio__D10_PIN       PINB
#define   pio__D10_PORT      PORTB
#define   pio__D11_PinID    11
#define   pio__D11_BIT       BIT5
#define   pio__D11_DDR       DDRB
#define   pio__D11_PIN       PINB
#define   pio__D11_PORT      PORTB
#define   pio__D12_PinID    12
#define   pio__D12_BIT       BIT6
#define   pio__D12_DDR       DDRB
#define   pio__D12_PIN       PINB
#define   pio__D12_PORT      PORTB
#define   pio__D13_PinID    13
#define   pio__D13_BIT       BIT7
#define   pio__D13_DDR       DDRB
#define   pio__D13_PIN       PINB
#define   pio__D13_PORT      PORTB
#define   pio__D14_PinID    14
#define   pio__D14_BIT       BIT1
#define   pio__D14_DDR       DDRJ
#define   pio__D14_PIN       PINJ
#define   pio__D14_PORT      PORTJ
#define   pio__D15_PinID    15
#define   pio__D15_BIT       BIT0
#define   pio__D15_DDR       DDRJ
#define   pio__D15_PIN       PINJ
#define   pio__D15_PORT      PORTJ
#define   pio__D16_PinID    16
#define   pio__D16_BIT       BIT1
#define   pio__D16_DDR       DDRH
#define   pio__D16_PIN       PINH
#define   pio__D16_PORT      PORTH
#define   pio__D17_PinID    17
#define   pio__D17_BIT       BIT0
#define   pio__D17_DDR       DDRH
#define   pio__D17_PIN       PINH
#define   pio__D17_PORT      PORTH
#define   pio__D18_PinID    18
#define   pio__D18_BIT       BIT3
#define   pio__D18_DDR       DDRD
#define   pio__D18_PIN       PIND
#define   pio__D18_PORT      PORTD
#define   pio__D19_PinID    19
#define   pio__D19_BIT       BIT2
#define   pio__D19_DDR       DDRD
#define   pio__D19_PIN       PIND
#define   pio__D19_PORT      PORTD
#define   pio__D20_PinID    20
#define   pio__D20_BIT       BIT1
#define   pio__D20_DDR       DDRD
#define   pio__D20_PIN       PIND
#define   pio__D20_PORT      PORTD
#define   pio__D21_PinID    21
#define   pio__D21_BIT       BIT0
#define   pio__D21_DDR       DDRD
#define   pio__D21_PIN       PIND
#define   pio__D21_PORT      PORTD
#define   pio__D22_PinID    22
#define   pio__D22_BIT       BIT0
#define   pio__D22_DDR       DDRA
#define   pio__D22_PIN       PINA
#define   pio__D22_PORT      PORTA
#define   pio__D23_PinID    23
#define   pio__D23_BIT       BIT1
#define   pio__D23_DDR       DDRA
#define   pio__D23_PIN       PINA
#define   pio__D23_PORT      PORTA
#define   pio__D24_PinID    24
#define   pio__D24_BIT       BIT2
#define   pio__D24_DDR       DDRA
#define   pio__D24_PIN       PINA
#define   pio__D24_PORT      PORTA
#define   pio__D25_PinID    25
#define   pio__D25_BIT       BIT3
#define   pio__D25_DDR       DDRA
#define   pio__D25_PIN       PINA
#define   pio__D25_PORT      PORTA
#define   pio__D26_PinID    26
#define   pio__D26_BIT       BIT4
#define   pio__D26_DDR       DDRA
#define   pio__D26_PIN       PINA
#define   pio__D26_PORT      PORTA
#define   pio__D27_PinID    27
#define   pio__D27_BIT       BIT5
#define   pio__D27_DDR       DDRA
#define   pio__D27_PIN       PINA
#define   pio__D27_PORT      PORTA
#define   pio__D28_PinID    28
#define   pio__D28_BIT       BIT6
#define   pio__D28_DDR       DDRA
#define   pio__D28_PIN       PINA
#define   pio__D28_PORT      PORTA
#define   pio__D29_PinID    29
#define   pio__D29_BIT       BIT7
#define   pio__D29_DDR       DDRA
#define   pio__D29_PIN       PINA
#define   pio__D29_PORT      PORTA
#define   pio__D30_PinID    30
#define   pio__D30_BIT       BIT7
#define   pio__D30_DDR       DDRC
#define   pio__D30_PIN       PINC
#define   pio__D30_PORT      PORTC
#define   pio__D31_PinID    31
#define   pio__D31_BIT       BIT6
#define   pio__D31_DDR       DDRC
#define   pio__D31_PIN       PINC
#define   pio__D31_PORT      PORTC
#define   pio__D32_PinID    32
#define   pio__D32_BIT       BIT5
#define   pio__D32_DDR       DDRC
#define   pio__D32_PIN       PINC
#define   pio__D32_PORT      PORTC
#define   pio__D33_PinID    33
#define   pio__D33_BIT       BIT4
#define   pio__D33_DDR       DDRC
#define   pio__D33_PIN       PINC
#define   pio__D33_PORT      PORTC
#define   pio__D34_PinID    34
#define   pio__D34_BIT       BIT3
#define   pio__D34_DDR       DDRC
#define   pio__D34_PIN       PINC
#define   pio__D34_PORT      PORTC
#define   pio__D35_PinID    35
#define   pio__D35_BIT       BIT2
#define   pio__D35_DDR       DDRC
#define   pio__D35_PIN       PINC
#define   pio__D35_PORT      PORTC
#define   pio__D36_PinID    36
#define   pio__D36_BIT       BIT1
#define   pio__D36_DDR       DDRC
#define   pio__D36_PIN       PINC
#define   pio__D36_PORT      PORTC
#define   pio__D37_PinID    37
#define   pio__D37_BIT       BIT0
#define   pio__D37_DDR       DDRC
#define   pio__D37_PIN       PINC
#define   pio__D37_PORT      PORTC
#define   pio__D38_PinID    38
#define   pio__D38_BIT       BIT7
#define   pio__D38_DDR       DDRD
#define   pio__D38_PIN       PIND
#define   pio__D38_PORT      PORTD
#define   pio__D39_PinID    39
#define   pio__D39_BIT       BIT2
#define   pio__D39_DDR       DDRG
#define   pio__D39_PIN       PING
#define   pio__D39_PORT      PORTG
#define   pio__D40_PinID    40
#define   pio__D40_BIT       BIT1
#define   pio__D40_DDR       DDRG
#define   pio__D40_PIN       PING
#define   pio__D40_PORT      PORTG
#define   pio__D41_PinID    41
#define   pio__D41_BIT       BIT0
#define   pio__D41_DDR       DDRG
#define   pio__D41_PIN       PING
#define   pio__D41_PORT      PORTG
#define   pio__D42_PinID    42
#define   pio__D42_BIT       BIT7
#define   pio__D42_DDR       DDRL
#define   pio__D42_PIN       PINL
#define   pio__D42_PORT      PORTL
#define   pio__D43_PinID    43
#define   pio__D43_BIT       BIT6
#define   pio__D43_DDR       DDRL
#define   pio__D43_PIN       PINL
#define   pio__D43_PORT      PORTL
#define   pio__D44_PinID    44
#define   pio__D44_BIT       BIT5
#define   pio__D44_DDR       DDRL
#define   pio__D44_PIN       PINL
#define   pio__D44_PORT      PORTL
#define   pio__D45_PinID    45
#define   pio__D45_BIT       BIT4
#define   pio__D45_DDR       DDRL
#define   pio__D45_PIN       PINL
#define   pio__D45_PORT      PORTL
#define   pio__D46_PinID    46
#define   pio__D46_BIT       BIT3
#define   pio__D46_DDR       DDRL
#define   pio__D46_PIN       PINL
#define   pio__D46_PORT      PORTL
#define   pio__D47_PinID    47
#define   pio__D47_BIT       BIT2
#define   pio__D47_DDR       DDRL
#define   pio__D47_PIN       PINL
#define   pio__D47_PORT      PORTL
#define   pio__D48_PinID    48
#define   pio__D48_BIT       BIT1
#define   pio__D48_DDR       DDRL
#define   pio__D48_PIN       PINL
#define   pio__D48_PORT      PORTL
#define   pio__D49_PinID    49
#define   pio__D49_BIT       BIT0
#define   pio__D49_DDR       DDRL
#define   pio__D49_PIN       PINL
#define   pio__D49_PORT      PORTL
#define   pio__D50_PinID    50
#define   pio__D50_BIT       BIT3
#define   pio__D50_DDR       DDRB
#define   pio__D50_PIN       PINB
#define   pio__D50_PORT      PORTB
#define   pio__D51_PinID    51
#define   pio__D51_BIT       BIT2
#define   pio__D51_DDR       DDRB
#define   pio__D51_PIN       PINB
#define   pio__D51_PORT      PORTB
#define   pio__D52_PinID    52
#define   pio__D52_BIT       BIT1
#define   pio__D52_DDR       DDRB
#define   pio__D52_PIN       PINB
#define   pio__D52_PORT      PORTB
#define   pio__D53_PinID    53
#define   pio__D53_BIT       BIT0
#define   pio__D53_DDR       DDRB
#define   pio__D53_PIN       PINB
#define   pio__D53_PORT      PORTB
#define   pio__D54_PinID    54
#define   pio__D54_BIT       BIT0
#define   pio__D54_DDR       DDRF
#define   pio__D54_PIN       PINF
#define   pio__D54_PORT      PORTF
#define   pio__D55_PinID    55
#define   pio__D55_BIT       BIT1
#define   pio__D55_DDR       DDRF
#define   pio__D55_PIN       PINF
#define   pio__D55_PORT      PORTF
#define   pio__D56_PinID    56
#define   pio__D56_BIT       BIT2
#define   pio__D56_DDR       DDRF
#define   pio__D56_PIN       PINF
#define   pio__D56_PORT      PORTF
#define   pio__D57_PinID    57
#define   pio__D57_BIT       BIT3
#define   pio__D57_DDR       DDRF
#define   pio__D57_PIN       PINF
#define   pio__D57_PORT      PORTF
#define   pio__D58_PinID    58
#define   pio__D58_BIT       BIT4
#define   pio__D58_DDR       DDRF
#define   pio__D58_PIN       PINF
#define   pio__D58_PORT      PORTF
#define   pio__D59_PinID    59
#define   pio__D59_BIT       BIT5
#define   pio__D59_DDR       DDRF
#define   pio__D59_PIN       PINF
#define   pio__D59_PORT      PORTF
#define   pio__D60_PinID    60
#define   pio__D60_BIT       BIT6
#define   pio__D60_DDR       DDRF
#define   pio__D60_PIN       PINF
#define   pio__D60_PORT      PORTF
#define   pio__D61_PinID    61
#define   pio__D61_BIT       BIT7
#define   pio__D61_DDR       DDRF
#define   pio__D61_PIN       PINF
#define   pio__D61_PORT      PORTF
#define   pio__D62_PinID    62
#define   pio__D62_BIT       BIT0
#define   pio__D62_DDR       DDRK
#define   pio__D62_PIN       PINK
#define   pio__D62_PORT      PORTK
#define   pio__D63_PinID    63
#define   pio__D63_BIT       BIT1
#define   pio__D63_DDR       DDRK
#define   pio__D63_PIN       PINK
#define   pio__D63_PORT      PORTK
#define   pio__D64_PinID    64
#define   pio__D64_BIT       BIT2
#define   pio__D64_DDR       DDRK
#define   pio__D64_PIN       PINK
#define   pio__D64_PORT      PORTK
#define   pio__D65_PinID    65
#define   pio__D65_BIT       BIT3
#define   pio__D65_DDR       DDRK
#define   pio__D65_PIN       PINK
#define   pio__D65_PORT      PORTK
#define   pio__D66_PinID    66
#define   pio__D66_BIT       BIT4
#define   pio__D66_DDR       DDRK
#define   pio__D66_PIN       PINK
#define   pio__D66_PORT      PORTK
#define   pio__D67_PinID    67
#define   pio__D67_BIT       BIT5
#define   pio__D67_DDR       DDRK
#define   pio__D67_PIN       PINK
#define   pio__D67_PORT      PORTK
#define   pio__D68_PinID    68
#define   pio__D68_BIT       BIT6
#define   pio__D68_DDR       DDRK
#define   pio__D68_PIN       PINK
#define   pio__D68_PORT      PORTK
#define   pio__D69_PinID    69
#define   pio__D69_BIT       BIT7
#define   pio__D69_DDR       DDRK
#define   pio__D69_PIN       PINK
#define   pio__D69_PORT      PORTK


#define   pio__PA_PORT       PORTA
#define   pio__PA_PIN        PINA
#define   pio__PA_DDR        DDRA
#define   pio__PB_PORT       PORTB
#define   pio__PB_PIN        PINB
#define   pio__PB_DDR        DDRB
#define   pio__PC_PORT       PORTC
#define   pio__PC_PIN        PINC
#define   pio__PC_DDR        DDRC
#define   pio__PD_PORT       PORTD
#define   pio__PD_PIN        PIND
#define   pio__PD_DDR        DDRD
#define   pio__PE_PORT       PORTE
#define   pio__PE_PIN        PINE
#define   pio__PE_DDR        DDRE
#define   pio__PF_PORT       PORTF
#define   pio__PF_PIN        PINF
#define   pio__PF_DDR        DDRF
#define   pio__PG_PORT       PORTG
#define   pio__PG_PIN        PING
#define   pio__PG_DDR        DDRG
#define   pio__PH_PORT       PORTH
#define   pio__PH_PIN        PINH
#define   pio__PH_DDR        DDRH
#define   pio__PJ_PORT       PORTJ
#define   pio__PJ_PIN        PINJ
#define   pio__PJ_DDR        DDRJ
#define   pio__PK_PORT       PORTK
#define   pio__PK_PIN        PINK
#define   pio__PK_DDR        DDRK
#define   pio__PL_PORT       PORTL
#define   pio__PL_PIN        PINL
#define   pio__PL_DDR        DDRL


#define   tim_PRESCALER_1     ((0 << CS12) | (0 << CS11) | (1 << CS10))
#define   tim_PRESCALER_8     ((0 << CS12) | (1 << CS11) | (0 << CS10))
#define   tim_PRESCALER_64    ((0 << CS12) | (1 << CS11) | (1 << CS10))
#define   tim_PRESCALER_256   ((1 << CS12) | (0 << CS11) | (0 << CS10))
#define   tim_PRESCALER_1024  ((1 << CS12) | (0 << CS11) | (1 << CS10))


#endif
